// English

//Don't change comment below, it's used by builder
//!!!!!!!! KEY START !!!!!!!!
export const en = {
	Home: "Home",
	Login: 'Sign in',
	Signin: "Sign in",
	CantHaveEmptyInputs: 'Please fill in all inputs',
	InvalidEmail: 'Invalid email',
	InvalidPhone: 'Invalid phone number',
	Signup: 'Sign up',
	Logout: 'Logout',
	Email: 'Email',
	Phone: 'Phone',
	Password: 'Password',
	FailedLogin: "User not found or wrong password",
	FailedSignup: "User already exists",
	TypePasswordHere: "Type password here",
	TypeEmailHere: "Type email here",
	NotRegisteredYetPlease: "Not Registered Yet? Please",
	Guest: 'Guest',
	Or: 'Or',
	ContinueAsGuest: 'Continue as Guest',
	SelectCountry: "Select Country",
	SelectLanguage: "Select Language",
	PassDontMatch: 'Passwords do not match',
	Address: 'Address',
	FirstName: 'First Name',
	SecondName: 'Second Name',
	Email1: 'Email1',
	Email2: 'Email2',
	Address1: 'Address 1',
	Address2: 'Address 2',
	Address1Placeholder: 'Address 1',
	Address2Placeholder: 'Address 2',
	PostCode: 'Post Code',
	IsCompany: 'Is Company?',
	CompanyName: 'Company Name',
	Country: 'Country',
	City: 'City',
	Area: 'Area',
	Phone1: 'Phone1',
	Phone2: 'Phone2',
	Profile: 'Profile',
	PersonalInfo: 'Personal Info',
	ChangePassword: 'Change Password',
	Language: 'Language',
	Currency: 'Currency',
	TimeZone: 'Time Zone',
	Interest: 'Interest',
	Info: 'Info',
	More: 'More',
	Cart: 'Cart',
	Category: 'Category',
	Categories: 'Categories',
	TopCategories: 'Main Categories',
	Orders: 'Orders',
	Order: 'Order',
	Product: 'Product',
	Products: 'Products',
	MyProducts: 'My Products',
	Reviews: 'Reviews',
	Signup: 'Sign up',
	Questions: 'Questions',
	Details: 'Details',
	Related: 'Related',
	Size: 'Size',
	AddToCart: 'Add to cart',
	Like: 'Like',
	Unlike: 'Unlike',
	WriteaReview: 'Write a review',
	SeeAll: 'See All',
	FeaturedDeals: 'Featured Deals',
	QuickDeals: 'Quick Deals',
	Deals: 'Deals',
	Name: 'Name',
	Facebook: 'Facebook',
	Twitter: 'Twitter',
	Website: 'Website',
	Gender: 'Gender',
	Birthday: 'Birthday',
	Search: 'Search',
	SelectPlace: 'Select Place',
	Cancel: 'Cancel',
	RatingsReviews: 'Ratings & Reviews',
	Likes: 'Likes',
	BuyNow: 'Buy Now',
	Buy: 'Buy',
	Specifications: 'Specifications',
	Delivery: 'Delivery',
	CustomersAlsoPurchased: 'Customers Also Purchased',
	Colors: 'Colors',
	DataSaved: 'Saved',
	LEFT: 'Left',
	AskaQuestions: 'Ask a Questions',
	Subtotal: 'Subtotal',
	Shipping: 'Shipping',
	Total: 'Total',
	MostHelpfulFirst: 'Most Helpful First',
	FullPrice: 'Full Price',
	GetStarted: 'Get Started',
	Skip: 'Skip',
	Article: 'Article',
	Articles: 'Articles',
	Liked: 'Liked',
	UnLiked: 'Un Liked',
	Done: 'Done',
	Notifications: 'Notifications',
	NOTIFICATIONS: 'NOTIFICATIONS',
	OrderNumber: 'Order Number',
	Items: 'Items',
	TrackingHistory: 'Tracking History',
	Tax: 'Tax',
	Summary: 'Summary',
	Discount: 'Discount',
	Quantity: 'Quantity',
	ExtraDetails1: 'Extra Details 1',
	ExtraDetails2: 'Extra Details 2',
	Item: 'Item',
	OrderCode: 'Order Code',
	CreatedDate: 'Created Date',
	Details: 'Details',
	Courier: 'Courier',
	Status: 'Status',
	DeliverDate: 'Deliver Date',
	SelectInterests: 'Select Interests',
	SelectGender: 'Select Gender',
	Select: 'Select',
	Pricing: 'Pricing',
	Settings: 'Settings',
	Description: 'Description',
	Media: 'Media',
	Delete: 'Delete',
	Price: 'Price',
	Rating: 'Rating',
	RealPrice: 'Real Price',
	SalePrice: 'Sale Price',
	SaleExpirationDate: 'Sale Expiration Date',
	notselected: 'not selected',
	notSelected: 'not Selected',
	MaxPurchaseCount: 'Max Purchase Count',
	Brand: 'Brand',
	selected: 'selected',
	ShortDescription: 'Short Description',
	NoneSelected: 'None Selected',
	NoShippingMethod: 'No shipping methods available. Please change or add an address',
	NoPaymentMethod: 'No payment methods available.',
	PickUpYourGender: 'Select Your Gender',
	PickUpYourInterests: 'Select Your Interests',
	PickUpYourCountry: 'Select Your Country',
	PickUpYourLanguage: 'Select Your Language',
	PickUpYour: 'Select Your',
	Interests: 'Interests',
	ResetPassword: 'Reset Password',
	Reset: 'Reset',
	NotVaildEmail: 'Enter Valid Email',
	EmailNotFound: 'Email Not Found',
	MaybeYouNeedTo: 'Maybe You Need To',
	NotValildCode: 'Invalid code',
	TooShortPassword: 'Too short password',
	InvalidPasswordFormat: "Password must contain at least one uppercase letter, lowercase letter, special character and number",
	PassDontMatch: 'Passwords do not match',
	PasswordConfirmation: 'Password Confirmation',
	FullName: 'Full Name',
	TypeNameHere: 'Type Name Here',
	Checkout: 'Checkout',
	Payment: 'Payment',
	Change: 'Change',
	Information: 'Information',
	RequiredOptions: 'Required Options',
	TypeOptionValue: 'Type option value here',
	MostRecent: 'Most recent',
	PhoneNotFound: 'Phone Not Found',
	Save: 'Save',
	SaveBtn: 'Save',
	ConfirmPassword: 'Confirm Password',
	NS_Reviews: 'Reviews',
	NoContent: "No content to show...",
	Visibility: 'Visibility',
	Type: 'Type',
	LoginWith: "Sign in With",
	Explore: "Explore",
	MonthlyOffers: 'Monthly Offers',
	Voucher: 'Voucher',
	ApplyVoucher: 'Apply Voucher',
	VoucherNumber: 'Voucher Number',
	PerOne: "Per One",
	Sale: "Sale",
	TypeVoucherHere: "Type Voucher Here",
	FlashDeals: "Flash Deals",
	CountDownDay: "Days",
	CountDownHour: "Hr",
	CountDownMin: "Mins",
	CountDownSec: "Seconds",
	DragAndDropYourLocation: 'Drag and drop to select location',
	FailedOrder: "Failed to place this order",
	PlacedOrder: "Order placed successfully",
	PleaseSelectAddress: 'Please select an address',
	PleaseSelectPayment: 'Please select a payment method',
	PleaseSelectShipping: 'Please select a shipping method',
	QuetionNow: 'Ask',
	PleaseWriteAQuestion: 'Please Write A Question',
	PleaseWriteAnswer: 'Please Write the Answer',
	Answer: 'Write Your Answer Here',
	Answers: 'Answers',
	OrderReview: 'Order Review',
	Review: 'Review',
	SeeMore: 'See More',
	MyLocation: "My Location",
	Optional: 'Optional',
	Chat: 'Chat',
	Confirm: 'Confirm',
	dataDeleted: 'Data Deleted',
	AreYouSure: 'Are You Sure',
	ReachedMaxQuantity: "Reached Max Quantity",
	ReachedMinQuantity: "Reached Min Quantity",
	SubStore: 'SubStore',
	SubStores: 'SubStores',
	HeaderBackTitle: "Back",
	FailedLocation: "Failed to fetch your location. Please check app permissions",
	ExitConfirmTitle: 'Exit app?',
	ExitConfirmBody: 'Are you sure you want to exit app now?',
	Yes: 'Yes',
	No: 'No',
	Note: 'Note',
	TypeNoteHere: "Type Note Here",
	LocationRequired: 'Please enter your location',
	PasswordChanged: 'Password Changed',
	CodeVerification: "Code Verification",
	AddressInstructions: "Please provide us with the following information to bring the best delivery experience for you",
	LoginTitle: "Enter your details to continue",
	SignupTitle: "This information is required for only one time",
	PasswordResetTitle: "Enter your details to continue",
	CompleteYourProfile: 'Complete Your Profile',
	FileTypeNotSupported: 'File Type Not Supported',
	EditingInLanguage: "Editing in",
	CancelOrder: 'Cancel Order',
	CantCancelOrder: 'Can\'t Cancel Order',
	RichTextEditor: 'Rich Text Editor',
	EditContentInEditor: 'Edit Content in Editor',
	QuestionReceived: 'Question Received, you will receive a notification when someone must answer your question',
	QuestionNotReceived: 'Question Has Been Send, Waiting for Admin Response...',
	YouMayLike: 'You May Like',
	Inbox: 'Inbox',
	Support: 'Support',
	BeFirstOne: 'Be First Answer',
	EnterFirstNameFirst: 'Enter Product Name First With Selected Language',
	BuyMoreSaveMore: 'Buy more. Save more.',
	ShippingCostEstimator: "Shipping Cost",
	ShippingCostEstimatorTitle: "Drag and drop the marker to get estimated delivery cost and time",
	ShippingCostEstimatorFail: "Can't get shipping cost estimate",
	PleaseWait: "Please Wait",
	TermsAndCondation: 'Using This App I Already Approve Terms Of Condition And Privacy Policy',
	TermsAndConditionsInCheckout: 'By Using This App I Already Approve Terms Of Condition And Privacy Policy',
	Terms: 'Terms',
	TermsText: 'terms Text here',
	MySales: 'My Sales',
	MyProductReviewMessage: "Your product will be available after admin approval",
	ShareAppWithYourFriend: 'Share App with your friend',
	CantOpenRightNow: 'Can\'t Open Right Now',
	ShippingCost: "Shipping Cost",
	ShippingTime: "Shipping Time",
	ProcessTime: "Process Time",
	AsSoonAsPossible: "As soon as possible",
	orSkipthisPage: 'Or Skip This Page',
	Collection: 'Collection',
	QRCodeReader: "QR Code",
	CheckingQRCode: "Checking QR Code",
	QRCodeReaderTitle: "Scan QR Code with your camera",
	AddAddress: 'Add New Address',
	Options: 'Options',
	Apply: 'Apply',
	Clear: 'Clear',
	PriceRange: 'Price',
	IncludeSearchProducts: 'Include Search Products',
	ETags: 'ETags',
	NewAddress: 'New Address',
	Warehouse: 'Warehouse',
	ContinueWithEmail: "Continue with email",
	ContinueWithPhone: "Continue with mobile number",
	ContinueWithFacebook: "Continue with Facebook",
	ContinueWithGoogle: "Continue with Google",
	EnableLocationInstruction: "We couldn't determine your location. Please make sure you have location service enabled and required permissions are given in app settings",
	AddedToCart: 'Added',
	ChangeYourAdrress: 'Change Your Address',
	CartSubtotal: 'Subtotal',
	PleaseWaitCheckout: 'Please wait while checking your info',
	AM: "AM",
	PM: "PM",
	New: 'New',
	Discounts: 'Discounts',
	ExpiryDate: "Expiry date",
	ApplyDate: "Apply date",
	Image: 'Image',
	File: 'File',
	CreateDate: 'Create Date',
	ShowInMap: 'Show in Map',
	Edit: "Edit",
	CantAddToCart: "Cannot add this product to cart",
	ShowOnMap: "Show on map",
	AddressInDetails: "Address in details",
	AddressInDetailsPlaceholder: "Your Address In Details",
	NoInternet: 'No Internet',
	OfflineNotice: 'Offline Notice',
	TryAgain: 'Try Again',
	MustSignupToPlaceOrder: "You must signup to place an order",
	VirtualMoney: 'Virtual Money',
	Spent: 'Spent',
	Balance: "Balance",
	SelectCity: 'Select City',
	SelectArea: 'Select Area',
	SelectCountry: 'Select Country',
	MaxRating: "Max Rating",
	Timemin: 'The Delivery Time For The Order :',
	CountDownMin2: 'Min',
	ProcessTime2: 'Preparation',
	ShippingTime2: 'Delivery',
	Off: 'Off',
	OrderNote: 'Note : ',
	Copied: 'Copied',
	TwoPushnotificaitonhavebeensent: 'Two Push notificaiton have been sent',
	TestNotification: 'Some fun with Push Notification',
	ShareYourApp: 'Share Your App',
	UpdateLocation: 'Update Location',
	OpenLocation: 'Open Location',
	Mange: 'Mange',
	OpenLocationAndCheckPermission: 'Open Location And Check Permission',
	OrderNow: 'Order Now',
	NameAddressPlaceHolder: ' ',
	AddressInDetailsPlaceHolder2: ' ',
	Email1PlaceHolder: ' ',
	Address2PlaceHolder2: ' ',
	CompanyNamePlaceHolder: ' ',
	TypeEmailHerePlaceHolder: ' ',
	TypeNameHerePlaceHolder: ' ',
	TypePasswordHerePlaceHolder: ' ',
	TypeOptionValuePlaceHolder: ' ',
	TypeFaceBookHerePlaceHolder: ' ',
	TypeTwitterHerePlaceHolder: ' ',
	TypeWebsiteHerePlaceHolder: ' ',
	EnterCompanyName: 'Enter Company Name',
	Address1NotVaild: 'Address1 Not Vaild',
	Address2NotVaid: 'Address2 Not Vaid',
	EmailNotVaild: 'Email Not Vaild',
	FirstNameNotVaild: 'Name Not Vaild',
	PasswordHasBeenResetSuccessfully: 'Password Has Been Reset Successfully',
	Roxiit: 'POWERED BY',
	TenantDescription: 'Best store in your area',
	HotDeals: 'Hot Deals',
	WishList: 'WishList',
	MostLikes: 'Most Likes',
	ShippingWarehouse: 'Warehouse',
	InviteFriends: 'Invite Friends',
	RedeemInviteCode: 'Redeem Invite Code',
	ItsNiceToSeeYou: 'Its Nice To See You',
	Redeem: 'Redeem',
	RedeemPlaceHolder: 'Type Here',
	TermsAndService: 'Terms and Conditions',
	Copy: 'Copy',
	Affiliate: 'Affiliate',
	InviteFriend: 'Invite Friend',
	History: 'History :',
	InviteYourFreind: 'Invite your friends and give them a gift, for every friend who complete their first purchase we will give you a gift',
	ShareAgift: 'Share A gift, Bring every one closer',
	RedeemTextDescription: 'Enter your friend invitation code, and click on redeem',
	Since: 'Since: ',
	FavouriteSubStores: 'Favourite SubStores',
	AddSubstore: 'Add Substore',
	ExtraPrice: 'Extra Price',
	UpdateProfile: 'Update Profile',
	MyStore: 'My Store',
	ProductsCount: 'Products Count',
	AddPoductsLabel: 'Add Product',
	AddStoreLaber: 'Add Store',
	SubStoreHassBeenCreated: 'Sub Store Hass Been Created',
	AddressInDetailsPlaceHolder: 'Address In Details',
	OrderMinValue: 'Minimun Order Value Is ',
	OrMore: 'Or More',
	AddMoreValue: 'Please Add More Products with value ',
	ToContinue: 'To Continue',
	ToContinuewithOffer: 'To Continue with Offer',
	FreeShippingWhen: 'Free Shipping on Orders More Than ',
	FreeShippingApplied: 'Free Shipping Applied',
	OrderMaxValue: 'Maximun Order Value Is ',
	OrLess: 'Or Less',
	RemoveMoreValue: 'Remove Product With Value ',
	MarkAsDefault: 'Mark As Default',
	PleaseSelectWarehouse: 'Please Select Warehouse',
	EstimatedShippingMsg: 'Estimated Shipping Time',
	CartIsEmpty: 'Empty Cart',
	StatusHistory: 'Status History',
	UpdateText: 'recommends that you update to the latest version',
	Update: 'Update',
	NoThanks: 'No Thanks',
	QuestionMark: ' ?',
	BuyNow: 'Buy Now',
	ProcessingFees: 'Processing Fees',
	RateOurApp: 'Rate your experience with us !',
	WhereCanWeImprove: 'Where can we improve ?',
	Okay: 'Okay',
	Excellent: 'Excellent !',
	ThanksForLovingUs: 'Thanks for loving us !',
	AnySuggestions: 'Any other suggestions ?',
	Submit: 'Submit',
	RateUsOnGoogle: 'Spread the world by rating us on Google Play',
	RateUs: 'Rate Us',
	SearchFor: 'Search For',
	Camera: 'Camera',
	Library: 'Library',
	Rate: 'Rate',
	RemindMeLater: 'Remind Me Later',
	ThankYou: 'Thank You',
	HappyToHearThat: 'We\'re so happy to hear that you love our app !  It\'d be really helpful if you rated us. Thanks for being a loyal customer!',
	Speed: 'Speed',
	Usability: 'Usability',
	Design: 'Design',
	Performance: 'Performance',
	Features: 'Features',
	Explanation: 'Explanation',
	Colors: 'Colors',
	Places: 'Places',
	AddMoreProducts: 'Add More Products',
	Complicated: 'Complicated',
	Payment: 'Payment',
	ImagesResolution: 'Images Resolution',
	ValidityExtendRequest: 'Validity Extend Request',
	ValidityExtendText: 'Admin Will Receve Notification For Your Validity Extend Request Are You Want to Confirm ?',
	ValidityExpiration: 'Validity Expiration',
	letsGo: 'Lets Go',
	InternalServerErrorTitle: 'Internal Server Error',
	InternalServerErrorBody: 'Internal Server Error, Please Try Again Later.',
	NotFoundServerErrorTitle: 'Data Not Found Error',
	NotFoundServerErrorBody: 'Requested Data Not Found.',
	MyCode: 'My Code',
	AskClerk: 'Ask clerk to scan you code to get our great discount',
	CommissionQRCode: 'Commission QR Code',
	Amount: 'Amount',
	Ok:'Ok'
};
//!!!!!!!! KEY END !!!!!!!!

//Don't change comment below, it's used by builder
//!!!!!!!! KEY START !!!!!!!!
export const ar = {
	Ok:'حسنا',
	Amount: 'الكمية',
	CommissionQRCode: 'عمولة كود الاستجابة السريعة',
	AskClerk: 'اطلب من البائع مسح الكود الخاص بك للحصول على العديد من الخصومات الخاصة',
	MyCode: 'الكود الخاص بي',
	NotFoundServerErrorTitle: 'خطأ في العثور على البيانات',
	NotFoundServerErrorBody: '.لم يتم العثور علي البيانات المطلوبة',
	InternalServerErrorTitle: 'خطأ داخلي في الخادم',
	InternalServerErrorBody: '.حدث خطأ داخلي برجاء معاودة المحاولة في وقت لاحق',
	letsGo: 'لنذهب',
	ValidityExpiration: 'صلاحيه المده',
	ValidityExtendText: 'المسؤل سوف يستلم اشعار ل طلب تمديد المده تاكيد الطلب ؟',
	ValidityExtendRequest: 'طلب تمديد المده',
	Library: 'المكتبه',
	Camera: 'كاميرا',
	Speed: 'السرعة',
	Usability: 'سهولة الاستخدام',
	Design: 'التصميم',
	Performance: 'الأداء',
	Features: 'الخصائص',
	Explanation: 'التفسير',
	Colors: 'الألوان',
	Places: 'الأماكن',
	AddMoreProducts: 'إضافة المزيد من المنتجات',
	Complicated: 'معقد',
	Payment: 'الدفع',
	ImagesResolution: 'دقة الصور',
	HappyToHearThat: 'نحن سعداء للغاية لسماع أنك تحب تطبيقنا! سيكون من المفيد حقا إذا قمت بتقييمنا. شكرا لكونك زبون مخلص',
	ThankYou: 'شكرا لك',
	Rate: 'قيم',
	RemindMeLater: 'ذكرني لاحقا',
	SearchFor: 'ابحث عن',
	RateUs: 'قيمنا',
	RateUsOnGoogle: 'انتشر للعالم بتصنيفنا على المتجر',
	Submit: 'إرسال',
	AnySuggestions: 'أي اقتراحات أخرى ؟',
	ThanksForLovingUs: '! شكرا لحبك لنا',
	Okay: 'حسنا',
	Excellent: '! ممتاز',
	WhereCanWeImprove: 'أين يمكننا التحسين ؟',
	RateOurApp: '! قيم تجربتك معنا',
	ProcessingFees: 'رسوم المعالجة',
	QuestionMark: ' ؟ ',
	Update: 'تحديث',
	NoThanks: 'لا شكرا',
	UpdateText: 'recommends that you update to the latest version',
	BuyNow: 'شراء الان',
	StatusHistory: 'تاريخ الحالة',
	CartIsEmpty: 'سله المشتريات فارغه',
	EstimatedShippingMsg: 'وقت الشحن',
	PleaseSelectWarehouse: 'من فضلك اختار المستودع',
	MarkAsDefault: 'وضع علامة كافتراضي',
	OrLess: 'او اقل',
	OrderMaxValue: 'لاتمام عملية الشراء يجب ان يكون قيمة الطلب ',
	ToContinuewithOffer: 'للاستمرار ف العرض',
	FreeShippingApplied: 'شحن مجاني مطبق',
	FreeShippingWhen: 'شحن مجاني عندما تتجاوز قيمة طلبك الي ',
	ToContinue: 'للاستمرر',
	RemoveMoreValue: 'قم بازالة منتجات بقيمة ',
	AddMoreValue: 'قم باضافة منتجات بقيمة ',
	OrderMinValue: 'لاتمام عملية الشراء يجب ان يكون قيمة الطلب ',
	OrMore: 'او اكثر',
	AddressInDetailsPlaceHolder: 'العنوان بالتفصيل',
	SubStoreHassBeenCreated: 'تم انشاء المتجر بنجاح',
	AddStoreLaber: 'اضافة متجر',
	AddPoductsLabel: 'اضافة منتجات',
	ProductsCount: 'عدد المنتجات',
	MyStore: 'متجري',
	UpdateProfile: 'تعديل الصفحة',
	AddSubStore: 'اضافة مستودع',
	ExtraPrice: 'تسعيره اضافية',
	FavouriteSubStores: 'المستودعات المفضلة',
	Since: 'منذ: ',
	RedeemTextDescription: 'ادخل كود الدعوة الخاص بصديقك, واضغط على تحقق',
	ShareAgift: 'شارك هدية',
	InviteYourFreind: 'ادع صديقك وامنحه هدية ولكل صديق يكمل أول عملية شراء سنقدم لك هدية',
	History: 'السجل :',
	InviteFriend: 'دعوة صديق',
	Affiliate: 'ضم',
	Copy: 'نسخ',
	TermsAndService: 'الشروط والاحكام',
	RedeemPlaceHolder: 'اكتب هنا',
	Redeem: 'تحقق',
	ItsNiceToSeeYou: 'من اللطيف زؤيتك',
	RedeemInviteCode: 'ادخال كود الدعوة',
	InviteFriends: 'دعوة اصدقاء',
	ShippingWarehouse: 'مستودع',
	MostLikes: 'الاكثر اعجابا',
	WishList: 'المفضلة',
	SaveBtn: 'حفظ',
	TenantDescription: 'افضل متجر الكتروني',
	HotDeals: 'اخر العروض',
	Roxiit: 'POWERED BY',
	PasswordHasBeenResetSuccessfully: 'تم إعادة تعيين كلمة المرور بنجاح',
	FirstNameNotVaild: 'الاسم غير صحيح',
	EmailNotVaild: 'الايميل غير صحيح',
	Address2NotVaid: 'عنوان 2 غير صحيح',
	Address1NotVaild: 'عنوان 1 غير صحيح ',
	EnterCompanyName: 'ادخل اسم الشركة',
	TypeWebsiteHerePlaceHolder: ' ',
	TypeTwitterHerePlaceHolder: ' ',
	TypeFaceBookHerePlaceHolder: ' ',
	TypeEmailHerePlaceHolder: ' ',
	NameAddressPlaceHolder: ' ',
	AddressInDetailsPlaceHolder2: ' ',
	Email1PlaceHolder: ' ',
	Address2PlaceHolder2: ' ',
	CompanyNamePlaceHolder: ' ',
	TypeNameHerePlaceHolder: ' ',
	TypePasswordHerePlaceHolder: ' ',
	TypeOptionValuePlaceHolder: ' ',
	OrderNow: 'طلب الان',
	OpenLocationAndCheckPermission: 'تاكد من انك قمت بفتح خدمة الموقع و من تصايرح التطبيق من الاعدادات',
	Mange: 'ادارة',
	OpenLocation: 'افتح خدمة الموقغ',
	UpdateLocation: 'تحديث الموقع',
	ShareYourApp: 'مشاركة التطبيق',
	TestNotification: 'بعض المرح مع الاشعارات',
	TwoPushnotificaitonhavebeensent: 'تم ارسال اشعارين الى جهازك',
	Copied: 'تم النسخ',
	OrderNote: 'ملاحظة : ',
	Off: 'وفر',
	ShippingTime2: 'توصيل',
	ProcessTime2: 'تحضير',
	CountDownMin2: 'د',
	Timemin: 'الزمن اللازم للتوصيل الطلب :',
	MaxRating: "اعلى تقييم",
	Spent: 'مُنفق',
	VirtualMoney: 'أموال افتراضية',
	Balance: "الرصيد",
	SelectCountry: 'اختار البلد',
	SelectArea: 'اختار المنطقة',
	SelectCity: 'اختار مدينة',
	MustSignupToPlaceOrder: "يجب عليك تسجيل الدخول قبل ان تتمكن من ارسال الطلب",
	AddressInDetails: "العنوان بالتفصيل",
	AddressInDetailsPlaceholder: " العنوان بالتفصيل ",
	ShowOnMap: "العرض على الخريطة",
	CantAddToCart: "لا يمكن اضافة هذا المنتج الى لعربة",
	TryAgain: 'حاول مجددا',
	OfflineNotice: 'تنبيه... جهازك غير متصل الى الانترنت',
	NoInternet: 'لا يوجد اتصال',
	Edit: "تعديل",
	ShowInMap: 'عرض على الخريطة',
	CreateDate: 'تاريخ الانشاء',
	File: 'ملف',
	Image: 'صورة',
	ExpiryDate: "تاريخ الانتهاء",
	ApplyDate: "تاريخ الاستخدام",
	Discounts: 'خصومات',
	New: 'جديد',
	AM: "صباحا",
	PM: "مساء",
	PleaseWaitCheckout: 'جاري فحص البيانات, من فضلك انتظر',
	AddedToCart: 'تمت الإضافة',
	CartSubtotal: 'المجموع',
	ChangeYourAdrress: 'تغير عنوان الشحن',
	EnableLocationInstruction: "لم نتمكن من التعرف على موقعك. من فضلك فعل خدمة الموقع وتأكد من الصلاحيات اللازمة من خلال الاعدادات",
	ContinueWithFacebook: "سجل عن طريق فيسبوك",
	ContinueWithGoogle: "سجل عن طريق جوجل",
	ContinueWithEmail: "سجل بواسطة البريد الالكتروني",
	ContinueWithPhone: "سجل برقم الجوال",
	ETags: 'الكلمات الدلالية',
	IncludeSearchProducts: 'تضمن بحث المنتجات',
	Apply: 'تطبيق',
	Clear: 'الغاء',
	PriceRange: 'السعر',
	Warehouse: 'المستودع',
	NewAddress: 'عنوان جديد',
	Options: 'الخيارات',
	AddAddress: 'اضافة عنوان جديد',
	CheckingQRCode: "جاري فحص رمز الاستجابة السريعة",
	QRCodeReaderTitle: "صور رمز الاستجابة السريعة بالكاميرا",
	QRCodeReader: "رمز الاستجابة السريعة",
	Collection: 'مجموعة',
	AsSoonAsPossible: "في اقرب وقت ممكن",
	ShippingCost: "تكلفة الشحن",
	ShippingTime: "وقت الشحن",
	ProcessTime: "وقت التحضير",
	orSkipthisPage: 'أو تخطي هذه الصفحة',
	CantOpenRightNow: 'لا يمكن تنفيذ هذا الان',
	ShareAppWithYourFriend: 'نشر التطبيق مع اصدقائك',
	MySales: 'مبيعاتي',
	MyProductReviewMessage: "المنتج سيكون متاح للبيع بعد موافقة الادمن",
	PleaseWait: "من فضلك انتظر",
	TermsText: 'الشروط هنا',
	Terms: 'الشروط',
	TermsAndCondation: 'باستخدام هذا التطبيق ، لقد وافقت بالفعل على الشروط والأحكام وسياسة الخصوصية',
	TermsAndConditionsInCheckout: 'باستخدام هذا التطبيق ، أوافق بالفعل على شروط الاستخدام وسياسة الخصوصية',
	BuyMoreSaveMore: 'اشتري اكثر و وفر اكثر',
	ShippingCostEstimatorFail: "لم نتمكن من عرض تكلفة الشحن",
	ShippingCostEstimatorTitle: "اسحب المؤشر على الخريطة لمعرفة تكلفة و وقت الشحن",
	ShippingCostEstimator: "تكلفة الشحن",
	EnterFirstNameFirst: 'ادخل اسم المنتج اولا بهذه اللغة',
	BeFirstOne: 'كن السباق وساعد بطرح الأسئلة و الأجوبة',
	EditingInLanguage: "التحرير باللغة",
	Support: 'الدعم',
	Inbox: 'الوارد',
	YouMayLike: 'قد يعجبك',
	QuestionNotReceived: 'تم ارسال السؤال, في انتظار موافقة الأدمن...',
	QuestionReceived: 'تم ارسال السؤال, سوف تستلم اشعار عندما يجب احد علي سؤالك ',
	EditContentInEditor: 'تعديل المحتوي بالمحرر',
	RichTextEditor: 'محرر النصوص',
	CantCancelOrder: 'لا يمكنك الغاء الطلب',
	CancelOrder: 'الغاء الطلب',
	FileTypeNotSupported: 'صيغة الملف غير مدعومة',
	LoginTitle: "قم بإدخال التفاصيل",
	SignupTitle: "هذه المعلومات مطلوبة لمرة واحدة فقط",
	PasswordResetTitle: "قم بإدخال التفاصيل",
	AddressInstructions: "من فضلك زودنا بالمعلومات التالية من اجل خدمة توصيل افضل لك",
	CompleteYourProfile: 'أكمل بيانات صفحتك الشخصية',
	CodeVerification: "التحقق من الرمز",
	PasswordChanged: 'تم تغير كلمة المرور',
	LocationRequired: 'من فضلك أدخل موقعك',
	Note: 'ملاحظة',
	TypeNoteHere: "اكتب ملاحظة هنا",
	Yes: 'نعم',
	No: 'لا',
	ExitConfirmBody: 'هل انت متأكد انك تريد الخروج من التطبيق الآن؟',
	ExitConfirmTitle: 'الخروج من التطبيق؟',
	FailedLocation: "لم نتمكن من التعرف على موقعك. من فضلك قم بفحص صلاحيات التطبيق",
	SubStores: 'فروع',
	SubStore: 'فرع',
	HeaderBackTitle: "رجوع",
	ReachedMaxQuantity: "لا يمكن زيادة الكمية عن ذلك",
	ReachedMinQuantity: "وصلت للحد الادنى من الكمية",
	AreYouSure: 'هل انت متأكد',
	dataDeleted: 'تم مسح البيانات',
	Confirm: 'تأكيد',
	Chat: 'محادثة',
	Optional: 'اختياري',
	MyLocation: "موقعي",
	SeeMore: 'مشاهدة المزيد',
	Review: "تقييم",
	OrderReview: 'تقييم الطلب',
	Answers: 'الاجابات',
	Answer: 'اكتب اجابتك هنا ',
	PleaseWriteAnswer: 'من فضلك اكتب الاجابة',
	PleaseWriteAQuestion: 'من فضلك اكتب سؤالك',
	QuetionNow: 'اسأل',
	PleaseSelectAddress: 'من فضلك اختار العنوان',
	PleaseSelectPayment: 'من فضلك اختار وسيلة الدفع',
	PleaseSelectShipping: 'من فضلك اختار وسيلة الشحن',
	PlacedOrder: "تم الطلب بنجاح",
	FailedOrder: "فشل في ارسال طلبك",
	DragAndDropYourLocation: 'اختر موقعك',
	CountDownDay: "يوم",
	CountDownHour: "ساعة",
	CountDownMin: "دقيقة",
	CountDownSec: "ثانية",
	FlashDeals: "عروض سريعة",
	TypeVoucherHere: "اكتب كود التخفيض هنا",
	VoucherNumber: 'كود التخفيض',
	ApplyVoucher: 'تطبيق كود التخفيض',
	Voucher: 'كود التخفيض',
	MonthlyOffers: 'عروض شهرية',
	Type: 'النوع',
	Visibility: 'الظهور',
	NS_Reviews: 'التقييمات',
	ConfirmPassword: 'تأكيد كلمة المرور',
	Save: 'وفر',
	PhoneNotFound: 'الهاتف غير موجود',
	TypeNameHere: 'اكتب الاسم هنا',
	FullName: 'الاسم بالكامل',
	PasswordConfirmation: 'تأكيد كلمة المرور',
	PassDontMatch: 'كلمة المرور غير مطابقة',
	InvalidPasswordFormat: " يجب ان تحتوي كلمة المرور على حرف كبير و حرف صغير و حرف خاص و رقم",
	TooShortPassword: 'كلمة المرور قصيرة',
	NotValildCode: 'الكود غير صالح',
	MaybeYouNeedTo: 'ربما تحتاج الي',
	EmailNotFound: 'البريد الالكتروني غير موجود',
	NotVaildEmail: 'ادخل بريد الكتروني صحيح',
	Reset: 'استرجاع',
	ResetPassword: 'استرجاع كلمة المرور',
	Interests: 'الاهتمامات',
	PickUpYour: 'اختار',
	PickUpYourLanguage: 'اختار لغتك',
	PickUpYourCountry: 'اختار بلدك',
	PickUpYourInterests: 'اختار الاهتمامات',
	PickUpYourGender: 'اختار النوع',
	NoneSelected: 'غير محدد',
	ShortDescription: 'وصف قصير',
	selected: 'محدد',
	Brand: 'موديل',
	MaxPurchaseCount: 'الحد الأقصى للمشتريات',
	notSelected: 'لم يحدد',
	notselected: 'لم يحدد',
	SaleExpirationDate: 'تاريخ الخصم',
	SalePrice: 'سعر الخصم',
	RealPrice: 'السعر الحقيقي',
	Rating: 'تقييم',
	Price: 'السعر',
	Delete: 'حذف',
	Media: 'ميديا',
	Description: 'الوصف',
	Settings: 'الاعدادات',
	Pricing: 'التسعير',
	Select: 'اختار',
	SelectGender: 'اختار النوع',
	SelectInterests: 'اختار الاهتمامات',
	DeliverDate: 'تاريخ الوصول',
	Status: 'الحالة',
	Courier: 'شركة الشحن',
	Details: 'التفاصيل',
	OrderCode: 'كود الطلب',
	Item: 'الوحدة',
	ExtraDetails1: 'تفاصيل إضافية 1',
	ExtraDetails2: 'تفاصيل إضافية 2',
	Quantity: 'الكمية',
	Discount: 'التخفيض',
	Summary: 'المختصر',
	Tax: 'الضريبة',
	TrackingHistory: 'تتبع الطلب',
	Items: 'عناصر الطلب',
	OrderNumber: 'رقم الطلب',
	NOTIFICATIONS: 'الاشعارات',
	Notifications: 'الاشعارات',
	Done: 'تم',
	UnLiked: 'إزالة اعجاب',
	Liked: 'اعجبك',
	Article: 'مقال',
	Articles: 'مقالات',
	Skip: 'تخطي',
	GetStarted: 'لنبدأ',
	FullPrice: 'كل السعر',
	MostHelpfulFirst: 'الاكثر مساعدة اولا',
	Total: 'الاجمال',
	Shipping: 'الشحن',
	Subtotal: 'حاصل الجمع ',
	AskaQuestions: 'اسأل سؤال',
	LEFT: 'متبقي',
	DataSaved: 'تم الحفظ',
	Colors: 'الالوان',
	CustomersAlsoPurchased: 'العملاء ايضا اشتروها',
	Delivery: 'توصيل',
	Specifications: 'مواصفات',
	BuyNow: 'شراء الان',
	Buy: 'شراء',
	Likes: 'الإعجابات',
	RatingsReviews: 'التقييم',
	Cancel: 'الغاء',
	SelectPlace: 'اختار المكان',
	Search: 'بحث',
	Birthday: 'تاريخ الميلاد',
	Gender: 'النوع',
	Website: 'موقع الكتروني',
	Twitter: 'تويتر',
	Facebook: 'فيس بوك',
	Name: 'الاسم',
	QuickDeals: 'عروض سريعة',
	Deals: 'عروض',
	FeaturedDeals: 'عروض مميزة',
	SeeAll: 'شاهد المزيد',
	WriteaReview: 'اكتب تقييم',
	Related: 'مشابه',
	Like: 'اعجاب',
	Unlike: 'ازالة اعجاب',
	AddToCart: 'اضف الى العربة',
	Size: 'الحجم',
	Details: 'تفاصيل',
	Questions: 'الاسئلة',
	Signup: 'انشاء حساب',
	Reviews: 'تقييمات',
	Product: 'منتج',
	Products: 'منتجات',
	MyProducts: 'منتجاتي',
	Orders: 'طلبات',
	Order: 'طلب',
	Categories: 'الفئات',
	TopCategories: 'الفئات الرئيسية',
	Category: 'الفئة',
	Home: "الرئيسية",
	Login: 'تسجيل الدخول',
	Signin: "تسجيل الدخول",
	CantHaveEmptyInputs: 'من فضلك قم بملء كل المدخلات',
	InvalidEmail: 'البريد الالكتروني غير صالح',
	InvalidPhone: 'الجوال غير صالح',
	Signup: 'انشاء حساب',
	Logout: 'تسجيل خروج',
	Email: 'البريد الالكتروني',
	Phone: 'الجوال',
	Password: 'كلمة المرور',
	FailedLogin: "المستخدم غير موجود او كلمة المرور غير صحيحة",
	FailedSignup: "المستخدم موجود بالفعل",
	TypePasswordHere: "اكتب كلمة المرور هنا",
	TypeEmailHere: "اكتب البريد الالكتروني هنا",
	NotRegisteredYetPlease: "ليس لديك حساب؟",
	Guest: 'زائر',
	Or: 'او',
	ContinueAsGuest: 'استكمل كزائر',
	SelectCountry: "اختار البلد",
	SelectLanguage: "اختار اللغة",
	PassDontMatch: 'كلمة المرور غير مطابقة',
	Address: 'عنوان',
	FirstName: 'الاسم الاول',
	SecondName: 'الاسم الثاني',
	Email1: 'بريد الكتروني 1',
	Email2: 'بريد الكتروني 2',
	Address1: 'عنوان 1',
	Address2: 'عنوان 2',
	Address1Placeholder: 'عنوان 1',
	Address2Placeholder: 'عنوان 2',
	PostCode: 'كود',
	IsCompany: 'شركة؟',
	CompanyName: 'اسم الشركة',
	Country: 'بلد',
	City: 'مدينة',
	Area: 'منطقة',
	Phone1: 'جوال 1',
	Phone2: 'جوال 2',
	Profile: 'الصفحة الشخصية',
	PersonalInfo: 'معلومات شخصية',
	ChangePassword: 'تغير كلمة المرور',
	Language: 'اللغة',
	Currency: 'العملة',
	TimeZone: 'التوقيت',
	Interest: 'الاهتمامات',
	Info: 'معلومات',
	More: 'المزيد',
	Cart: 'السلة',
	NoShippingMethod: 'لا يوجد وسائل شحن. من فضلك قم بتحديث العنوان أو قم بإضافة عنوان جديد',
	NoPaymentMethod: 'لا يوجد وسائل دفع متاحة',
	Checkout: 'الدفع',
	Payment: 'الدفع',
	Change: 'تغيير',
	Information: 'معلومات',
	RequiredOptions: 'خيارات ضرورية',
	TypeOptionValue: 'ادخل القيمة هنا',
	MostRecent: 'الاحدث',
	NoContent: "لا يوجد محتوى..",
	LoginWith: "دخول بواسطة",
	Explore: "اكتشف",
	PerOne: "للواحدة",
	Sale: "تخفيض",
};
//!!!!!!!! KEY END !!!!!!!!


//Don't change comment below, it's used by builder
//!!!!!!!! KEY START !!!!!!!!
export const fr = {
	Home: "ACCEUIL",
	Login: "se connecter",
	Signin: "se connecter",
	CantHaveEmptyInputs: "Veuillez remplir toutes les données",
	InvalidEmail: "Email invalide",
	InvalidPhone: "Numero invalide",
	Signup: "s'inscrire",
	Logout: "se déconecter",
	Email: "Email",
	Phone: "téléphone",
	Password: "Mot de passe",
	FailedLogin: "utilisateur inconnue ou mot de passe incorrect",
	FailedSignup: "utilisateur existant",
	TypePasswordHere: "écrire mot de passe ici",
	TypeEmailHere: "écrire email ici",
	NotRegisteredYetPlease: "pas encore enregistrer ?",
	Guest: "inviter",
	Or: "Ou",
	ContinueAsGuest: "Continuer autant qu'inviter",
	SelectCountry: "séléctionner pays",
	SelectLanguage: "séléctionner langue",
	PassDontMatch: "mot de passe non similaire",
	Address: "adresse",
	FirstName: "Prénom",
	SecondName: "Nom",
	Email1: "Email1",
	Email2: "Email2",
	Address1: "Address 1",
	Address2: "Address 2",
	Address1Placeholder: "Address 1",
	Address2Placeholder: "Address 2",
	PostCode: "code postale",
	IsCompany: "Vous êtes un professionnel ?",
	CompanyName: "Nom de l'entreprise",
	Country: "Pays",
	City: "wilaya",
	Area: "Daîra",
	Phone1: "Phone1",
	Phone2: "Phone2",
	Profile: "Profile",
	PersonalInfo: "information personnel",
	ChangePassword: "changer mot de passe",
	Language: "Language",
	Currency: "Devise",
	TimeZone: "fuseau horaire",
	Interest: "intéresser",
	Info: "info",
	More: "plus",
	Cart: "Panier",
	Category: "catégorie",
	Categories: "catégories",
	TopCategories: "top catégories",
	Orders: "achats",
	Order: "acheter",
	Product: "produit",
	Products: "produits",
	MyProducts: "mes produits",
	Reviews: "Commentaires",
	Questions: "Questions",
	Details: "Details",
	Related: "Similaire",
	Size: "taille",
	AddToCart: "ajouter au panier",
	Like: "J'aime",
	Unlike: "j'aime pas",
	WriteaReview: "écrire un commentaire",
	SeeAll: "Voir tout",
	FeaturedDeals: "Produits les plus vendu",
	QuickDeals: "Offres rapides",
	Deals: "offres",
	Name: "Nom",
	Facebook: "Facebook",
	Twitter: "Twitter",
	Website: "site web",
	Gender: "Genre",
	Birthday: "date de naissance",
	Search: "recherche",
	SelectPlace: "Sélectionnez un lieu",
	Cancel: "Annuler",
	RatingsReviews: "Évaluations et commentaires",
	Likes: "j'aimes",
	BuyNow: "acheter maintenant",
	Buy: "acheter",
	Specifications: "spécification",
	Delivery: "livraison",
	CustomersAlsoPurchased: "Les clients ont également acheté",
	Colors: "Couleurs",
	DataSaved: "Enregistrer",
	LEFT: "quitter",
	AskaQuestions: "poser une question",
	Subtotal: "total",
	Shipping: "livraison",
	Total: "total",
	MostHelpfulFirst: "Le plus utile d'abord",
	FullPrice: "tout les prix",
	GetStarted: "Débuter",
	Skip: "Echapper",
	Article: "Article",
	Articles: "Articles",
	Liked: "Aimées",
	UnLiked: "Moins aimées",
	Done: "Fait",
	Notifications: "Notifications",
	NOTIFICATIONS: "NOTIFICATIONS",
	OrderNumber: "Numéro de commande",
	Items: "Articles",
	TrackingHistory: "Historique de suivi",
	Tax: "TVA",
	Summary: "Sommaire",
	Discount: "Remise",
	Quantity: "quantité",
	ExtraDetails1: "Détails supplémentaires 1",
	ExtraDetails2: "Détails supplémentaires 2",
	Item: "Article",
	OrderCode: "Numéro de commande",
	CreatedDate: "date de création",
	Courier: "Courier",
	Status: "Status",
	DeliverDate: "date de livraison",
	SelectInterests: "Sélectionnez intérêt",
	SelectGender: "sélectionnez le sexe",
	Select: "Select",
	Pricing: "prix",
	Settings: "paramétre",
	Description: "description",
	Media: "Media",
	Delete: "supprimer",
	Price: "prix",
	Rating: "noter",
	RealPrice: "prix de base",
	SalePrice: "prix de vente",
	SaleExpirationDate: "expiration de l'annonce",
	notselected: "non selectioner",
	notSelected: "non selectioner",
	MaxPurchaseCount: "Nombre d'achat maximum",
	Brand: "Marque",
	selected: "sélectioner",
	ShortDescription: "petite description",
	NoneSelected: "non selectioner",
	NoShippingMethod: "Aucune méthode d'expédition disponible. Veuillez changer ou ajouter une adresse",
	NoPaymentMethod: "Aucun mode de paiement disponible.",
	PickUpYourGender: "Sélectionnez votre sexe",
	PickUpYourInterests: "Sélectionnez vos intérêt",
	PickUpYourCountry: "sélectionnez pays",
	PickUpYourLanguage: "sélectionnez langue",
	PickUpYour: "sélectionnez vôtres",
	Interests: "intérêt",
	ResetPassword: "modifier mot de passe",
	Reset: "modifier",
	NotVaildEmail: "Entrer Email valide",
	EmailNotFound: "Email non trouver",
	MaybeYouNeedTo: "Peut etre avez-vous besoin",
	NotValildCode: "code invalide",
	TooShortPassword: "mot de passe trop court",
	InvalidPasswordFormat: "Le mot de passe doit contenir au moins une lettre majuscule, une lettre minuscule, un caractère spécial et un nombre",
	PasswordConfirmation: "confirmer Mot de passe",
	FullName: "Nom",
	TypeNameHere: "Ecrire nom ici",
	Checkout: "Sortir",
	Payment: "Payment",
	Change: "changer",
	Information: "Information",
	RequiredOptions: "option requise",
	TypeOptionValue: "Saisissez la valeur de l'option ici",
	MostRecent: "les plus récents",
	PhoneNotFound: "Numéro non trouver",
	Save: "enregistrer",
	ConfirmPassword: "Confirmer Mot de passe",
	NS_Reviews: "avis",
	NoContent: "Aucun contenu à afficher ...",
	Visibility: "Vue",
	Type: "Type",
	LoginWith: "se connecter avec",
	Explore: "Recherche",
	MonthlyOffers: "offres du mois",
	Voucher: "facture",
	ApplyVoucher: "appliquer la facture",
	VoucherNumber: "facture N°",
	PerOne: "par un",
	Sale: "Vendre",
	TypeVoucherHere: "taper la facture ici",
	FlashDeals: "offres flash",
	CountDownDay: "jours",
	CountDownHour: "heures",
	CountDownMin: "minuts",
	CountDownSec: "Seconds",
	DragAndDropYourLocation: "poser localisation",
	FailedOrder: "Impossible de passer cette commande",
	PlacedOrder: "commande passer",
	PleaseSelectAddress: "sélectionner une address",
	PleaseSelectPayment: "sélectionner methodes de payement",
	PleaseSelectShipping: "Veuillez choisir un mode de livraison",
	QuetionNow: "question ?",
	PleaseWriteAQuestion: "SVP ecrire une question",
	PleaseWriteAnswer: "SVP ecrire une reponse",
	Answer: "écrire une reponse ici",
	Answers: "réponse",
	OrderReview: "Examen de la commande",
	Review: "commande",
	SeeMore: "Voir plus",
	MyLocation: "Ma localisation",
	Optional: "Option",
	Chat: "Chat",
	Confirm: "confirmer",
	dataDeleted: "date suppression",
	AreYouSure: "êtes vous sur",
	ReachedMaxQuantity: "Quantité maximale atteinte",
	ReachedMinQuantity: "Quantité minimum",
	SubStore: "SubStore",
	SubStores: "SubStores",
	HeaderBackTitle: "retour",
	FailedLocation: "Impossible de récupérer votre position. Veuillez vérifier les autorisations des applications",
	ExitConfirmTitle: "Quitter l'application?",
	ExitConfirmBody: "Voulez-vous vraiment quitter l'application maintenant?",
	Yes: "Oui",
	No: "Non",
	Note: "Note",
	TypeNoteHere: "Ecrire la note ici",
	LocationRequired: "Entrer localisation",
	PasswordChanged: "Mot de passe changer",
	CodeVerification: "code de vérification",
	AddressInstructions: "Veuillez nous fournir les informations suivantes pour vous offrir la meilleure expérience de livraison",
	LoginTitle: "Entrez vos coordonnées pour continuer",
	SignupTitle: "Cette information n'est requise qu'une seule fois",
	PasswordResetTitle: "Entrez vos coordonnées pour continuer",
	CompleteYourProfile: "Complète ton profil",
	FileTypeNotSupported: "Type de fichier non pris en charge",
	EditingInLanguage: "Edition dans",
	CancelOrder: "annuler la commande",
	CantCancelOrder: "impossible d'annuler la commande",
	RichTextEditor: "Éditeur de texte enrichi",
	EditContentInEditor: "Modifier le contenu dans l'éditeur",
	QuestionReceived: "Question reçue, vous recevrez une notification lorsque quelqu'un devra répondre à votre question",
	QuestionNotReceived: "La question a été envoyée, en attente de la réponse de l'administrateur ...",
	YouMayLike: "Vous pouvez Liker",
	Inbox: "Boite de récéption",
	Support: "Support",
	BeFirstOne: "soyez le premier a répondre",
	EnterFirstNameFirst: "Entrez d'abord le nom du produit ",
	BuyMoreSaveMore: "Acheter plus. Économisez plus.",
	ShippingCostEstimator: "Frais de port",
	ShippingCostEstimatorTitle: "Faites glisser et déposez le marqueur pour obtenir le coût et le temps de livraison",
	ShippingCostEstimatorFail: "Impossible d'obtenir une estimation des frais d'expédition",
	PleaseWait: "Patientez",
	TermsAndCondation: "En utilisant cette application, j'approuve déjà les conditions générales et la politique de confidentialité",
	Terms: "Terms",
	TermsText: "terms Text ici",
	MySales: "Mes ventes",
	MyProductReviewMessage: "Votre produit sera disponible après l'approbation de l'administrateur",
	ShareAppWithYourFriend: "Partager l'application avec vos amis",
	CantOpenRightNow: "Impossible d'ouvrir maintenant",
	ShippingCost: "Frais de port",
	ShippingTime: "Temps d'expédition",
	ProcessTime: "Temps de traitement",
	AsSoonAsPossible: "Au plus tot possible",
	orSkipthisPage: "Ou sautez cette page",
	Collection: "Collection",
	QRCodeReader: "QR Code",
	CheckingQRCode: "Check QR Code",
	QRCodeReaderTitle: "Scanner code QR avec votre camera",
	AddAddress: "ajouter une  nouvelle address",
	Options: "Options",
	Apply: "appliquer",
	Clear: "supprimer",
	PriceRange: "prix",
	IncludeSearchProducts: "inclure les produits rechercher",
	ETags: "ETags",
	NewAddress: "Nouvelle address",
	Warehouse: "Entrepôt",
	ContinueWithEmail: "Continuez avec l'Email",
	ContinueWithPhone: "Continuez avec le numero",
	ContinueWithFacebook: "Continuez avec Facebook",
	ContinueWithGoogle: "Continuez avec google",
	EnableLocationInstruction: "Nous n'avons pas pu déterminer votre emplacement. Veuillez vous assurer que le service de localisation est activé et que les autorisations requises sont accordées dans les paramètres de l'application",
	AddedToCart: "Ajouter",
	ChangeYourAdrress: "Changer d'address",
	CartSubtotal: "Total",
	PleaseWaitCheckout: "Veuillez patienter pendant la vérification de vos informations",
	AM: "AM",
	PM: "PM",
	New: "Nouveau",
	Discounts: "Remises",
	ExpiryDate: "date d'expiration",
	ApplyDate: "appliquer la date",
	Image: "Image",
	File: "fichier",
	CreateDate: "créer date",
	ShowInMap: "voir sur map",
	Edit: "Editer",
	CantAddToCart: "Impossible d'ajouter ce produit au panier",
	ShowOnMap: "voir sur map",
	AddressInDetails: "address en détails",
	AddressInDetailsPlaceholder: "votre address en détails",
	NoInternet: "pas d'internet",
	OfflineNotice: "Avis hors ligne",
	TryAgain: "Réessayer",
	MustSignupToPlaceOrder: "Vous devez vous inscrire pour passer une commande",
	VirtualMoney: "Argent virtuel",
	Spent: "dépense",
	Balance: "Balance",
	SelectCity: "Select wilaya",
	SelectArea: "Select daîra",
	MaxRating: "Évaluation maximale",
	Timemin: "Le délai de livraison pour la commande:",
	CountDownMin2: "Minutes",
	ProcessTime2: "Preparation",
	ShippingTime2: "livraison",
	Off: "eteint",
	OrderNote: "Note : ",
	Copied: "copier",
	TwoPushnotificaitonhavebeensent: "Deux notifications push ont été envoyées",
	TestNotification: "Notification de test",
	ShareYourApp: "Partagez votre application",
	UpdateLocation: "Mettre à jour l'emplacement",
	OpenLocation: "Lieu ouvert",
	Mange: "Probléme",
	OpenLocationAndCheckPermission: "Ouvrir l'emplacement et vérifier l'autorisation",
	OrderNow: "Commandez maintenant"
};
//!!!!!!!! KEY END !!!!!!!!


// Languages
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !! NOTE !! keep the following array in one line it will be replaced by builder  !! NOTE !!																                                          !!!
//                                                                                                                                                                                                    !!!			
export const Languages = [{ key: 1, label: 'العربية', code: 'ar', isRTL: true, isDefault: false, obj: ar }, { key: 2, label: 'English', code: 'en', isRTL: false, isDefault: true, obj: en }, { key: 5, label: 'French', code: 'fr', isRTL: false, isDefault: false, obj: fr },];   //!!!
//                                                                                             	                                                                                       			      !!!
// !! NOTE !! keep the previous array in one line !! NOTE !!	                                                                                                               			              !!!			
//                                                                                                                                                                                        			  !!!			
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!